version: '3.7'
services:
  database-sql:
    container_name: sql-database
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
      - mynet
    ports:
      - "3306:3306"
    command:  --init-file /docker-entrypoint-initdb.d/initdb.sql  --default-authentication-plugin=mysql_native_password 
 
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456Aa@
      - MYSQL_HOST=%
      - MYSQL_DATABASE=comparativo
      - MYSQL_RANDOM_ROOT_PASSWORD=false
      - host_cache_size=0
     
  redis-service:
    container_name: redis-database
    image: 'bitnami/redis:latest'
    networks:
      - mynet
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  unipot-docker:
    build:
      context: ./UNIpot
      dockerfile: Dockerfile
    container_name: unipot-docker
    networks:
      - mynet
    expose:
      - '8001'
    ports:
      - '8001:8001'
  user-api-docker:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: user-api-docker
    links:
      - 'database-sql'
      - 'redis-service'
      - 'unipot-docker'
    networks:
      - mynet
    environment:
      - port=8002
      - unipot_host=unipot-docker
      - redis_host=redis-service
      - mysql_host=database-sql
    expose:
      - '8002'
    ports:
      - '8002:8002'
    depends_on:
      - 'database-sql'
      - 'redis-service'
      - 'unipot-docker'
networks:
  mynet:
    driver: bridge
    